level_1 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XR XXXXXXX      E   XXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX L      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X L E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXERX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX                     X",
            "XX          EXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XXL          XXXX       X",
            "XXXE                   LX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_2 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XR                E L  XX",
            "XX      XXXXXXXXXXXXX   X",
            "XXX  X  X    XXX  X X   X",
            "X   XXXXX    XX  XX X   X",
            "X       XXXX    XXX X  XX",
            "XXXXXX  XXXX    X   X   X",
            "X      XXXXXXX   XXXXX  X",
            "X  X   XXXXXXXXX   E    X",
            "X XXX  XXXXXXXX    XXXX X",
            "X XXXX  XX       XXX    X",
            "X XXXXX     X    RXX  XXX",
            "X XXXXX  XXXX      X   RX",
            "X X     XXXXXXXX   X XX X",
            "X  RX      XXX     X XX X",
            "X  XXX  X     P   XX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  X     E    LX",
            "XE XXX  XX XX  XXXXX  XXX",
            "XXXXXX  XX     XXXXX  XXX",
            "XXLE    XX  XXX  E     XX",
            "XX XXXXXX   XX  XXXX X  X",
            "X E        LXX   XXX X TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_3 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX      E   XXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX R      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X L E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXERX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX             R       X",
            "XX          EXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XXL          XXXX       X",
            "XXXE                   LX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_4 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XR                E L  XX",
            "XX      XXXXXXXXXXXXX   X",
            "XXX  X  X    XXX  X X   X",
            "X   XXXXX    XX  XX X   X",
            "X       XXXX    XXX X  XX",
            "XXXXXX  XXXX    X   X   X",
            "X      XXXXXXX   XXXXX  X",
            "X  X   XXXXXXXXX   E    X",
            "X XXX  XXXXXXXX    XXXX X",
            "X XXXX  XX       XXX    X",
            "X XXXXX     X     XX  XXX",
            "X XXXXX  XXXX      X   RX",
            "X X     XXXXXXXX   X XX X",
            "X  RX      XXX     X XX X",
            "X  XXX  X     P   XX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  X     E    LX",
            "XE XXX  XX XX  XXXXX  XXX",
            "XXXXXX  XX     XXXXX  XXX",
            "XXLE    XX  XXX  E     XX",
            "XX XXXXXX   XX  XXXX X  X",
            "X E        LXX   XXX X RX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_5 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX      E  LXXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX R      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X L E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXERX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX                     X",
            "XX          EXXXXXXXXXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XXL          XXXX       X",
            "XXXE                   RX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_6 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XL                E R  XX",
            "XX      XXXXXXXXXXXXX   X",
            "XXX  X  X    XXX  X X   X",
            "X   XXXXX    XX  XX X   X",
            "X       XXXX    XXX X  XX",
            "XXXXXX  XXXX    X   X   X",
            "X      XXXXXXX   XXXXX  X",
            "XL X   XXXXXXXXX   E    X",
            "X XXX  XXXXXXXX    XXXX X",
            "X XXXX  XX       XXX    X",
            "X XXXXX     X     XX  XXX",
            "X XXXXX  XXXX      X   RX",
            "X X     XXXXXXXX   X XX X",
            "X  LX      XXX     X XX X",
            "X  XXX  X     P   XX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  XXXX XXX XX X",
            "X  XXX  XX  X     E    RX",
            "XE XXX  XX XX  XXXXX  XXX",
            "XXXXXX  XX     XXXXX  XXX",
            "XXLE    XX  XXX  E     XX",
            "XX XXXXXX   XX  XXXX X  X",
            "X E         XX   XXX X RX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

blank_maze = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]